image: Visual Studio 2017
environment:
  matrix:
    - node_version: '8'
    - node_version: '10'
version: '{build}'
branches:
  only:
    - master
install:
  - ps: 'Install-Product node $env:node_version'
cache:
  - node_modules
  - '%LOCALAPPDATA%\Yarn'
build_script:
  - yarn install --frozen-lockfile
test_script:
  - yarn test